--Seguimiento
DELIMITER //

DROP PROCEDURE IF EXISTS SP_HISTORIAL_PAGOS //

CREATE PROCEDURE SP_HISTORIAL_PAGOS(IN ID_DEPARTAMENTO INT)
BEGIN
    SELECT MONTO, FECHA_PAGO, MÉTODO_PAGO, ESTADO FROM PAGO
    WHERE DEPARTAMENTO_ID_DEPARTAMENTO = ID_DEPARTAMENTO;
END //

DELIMITER ;

DELIMITER //

DROP PROCEDURE IF EXISTS SP_REPORTE_PAGOS //

CREATE PROCEDURE SP_REPORTE_PAGOS(IN ID_DEPARTAMENTO INT, IN ANIO INT, IN MES INT)
BEGIN
    SELECT MONTO, FECHA_PAGO, MÉTODO_PAGO, ESTADO FROM PAGO
    WHERE DEPARTAMENTO_ID_DEPARTAMENTO = ID_DEPARTAMENTO
    AND YEAR(FECHA_PAGO) = ANIO
    AND MONTH(fecha_pago) = MES;
END //

DELIMITER ;